CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    namefull VARCHAR(50) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    phone VARCHAR(15) NOT NULL,
    birth_date DATE NOT NULL,
    address VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    is_admin VARCHAR(255) NOT NULL,
    is_disable VARCHAR(255) NOT NULL,
    create_dt TIMESTAMP NOT NULL,
    update_dt TIMESTAMP NOT NULL
);