CREATE TABLE rents(
        Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        book_id BIGINT NOT NULL,
        rent_date DATE NOT NULL,
        return_period DATE,
        return_date DATE NOT NULL,
        status VARCHAR(50) NOT NULL,
        create_dt TIMESTAMP NOT NULL,
        update_dt TIMESTAMP NOT NULL,
        CONSTRAINT fk_rents_user
                FOREIGN KEY (user_id)
                REFERENCES users(id),

            CONSTRAINT fk_rents_book
                FOREIGN KEY (book_id)
                REFERENCES books(id)


);